---
abstract: 'Wrapper for text to number conversion modules of various languages in the Lingua::XXX hierarchy.'
author:
  - 'PetaMem s.r.o. <info@petamem.com>'
build_requires:
  Test::More: 0
  perl: v5.10.0
  utf8: 0
configure_requires:
  ExtUtils::MakeMaker: 6.30
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.300028, CPAN::Meta::Converter version 2.120921'
license: open_source
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Lingua-Word2Num
requires:
  Carp: 0
  Lingua::AFR::Word2Num: 0
  Lingua::CES::Word2Num: 0
  Lingua::DEU::Word2Num: 0
  Lingua::ENG::Word2Num: 0
  Lingua::EUS::Word2Num: 0
  Lingua::FRA::Word2Num: 0
  Lingua::IND::Words2Nums: 0
  Lingua::ITA::Word2Num: 0
  Lingua::JPN::Word2Num: 0
  Lingua::NLD::Word2Num: 0
  Lingua::NOR::Word2Num: 0
  Lingua::POL::Word2Num: 0
  Lingua::POR::Words2Nums: 0
  Lingua::RUS::Word2Num: 0
  Lingua::SPA::Word2Num: 0
  Lingua::SWE::Word2Num: 0
  Lingua::ZHO::Word2Num: 0
  Perl6::Export::Attrs: 0
  Readonly: 0
  strict: 0
  warnings: 0
version: 0.0477
